repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
  # - repo: https://github.com/gherynos/pre-commit-java
  #   rev: v0.1.0 # Use the ref you want to point at
  #   hooks:
  #     - id: pmd
  #     - id: cpd
  #     - id: checkstyle
  #       #       exclude: "**/domain/*,**/*Form.java,**/*Value.java,**/*Request.java,**/*Properties.java,**/Application.*,**/*Initializer.*"
  #       args: ["-c", "checkstyle.xml"]
