# see: https://www.appveyor.com/docs/appveyor-yml/
version: "1.0.{build}"
image: Visual Studio 2019
branches:
  # whitelist
  # only:
  #   - master
  # blacklist
  except:
    - gh-pages
skip_tags: true
clone_depth: 1
environment:
  MAVEN_VERSION: 3.8.1
  JAVA_HOME: C:\Program Files\Java\jdk17
  # matrix:
  #   - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  #   - JAVA_HOME: C:\Program Files\Java\jdk11

services:
  - mongodb
install:
  # - ps: |
  #     Add-Type -AssemblyName System.IO.Compression.FileSystem
  #     if (!(Test-Path -Path "C:\maven" )) {
  #       (new-object System.Net.WebClient).DownloadFile(
  #         'http://www.us.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip',
  #         'C:\maven-bin.zip'
  #       )
  #       [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
  #     }
  - cmd: |
      choco install 7zip -y
      curl -o jdk17.zip -L https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.1+12/OpenJDK17U-jdk_x64_windows_hotspot_17.0.1_12.zip
      7z x jdk17.zip -o"C:\Program Files\Java\"
      dir "C:\Program Files\Java\"
  - cmd: SET PATH=%JAVA_HOME%\bin;%PATH%
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn clean package -DskipTests
test_script:
  - mvn clean install
cache:
  - C:\Users\appveyor\.m2\ -> pom.xml
